web:
  extends:
    file: ../common/services.yml
    service: server
  links:
    - redis
    - mongo
  ports:
    - "3000:3000"

  environment:
    DATABASE_URL: mongodb://mongo/bootrank
    REDIS_URL: redis://redis/10
    PORT: 3000
  env_file:
    - ../../.env

redis:
  extends:
    file: ../common/services.yml
    service: redis
  ports:
    - "6379:6379"

mongo:
  extends:
    file: ../common/services.yml
    service: mongodb
  ports:
    - "27017:27017"


